### ISSUE TITLE
Test title

### ISSUE THREAD

**Issue by githubUserTest12** [BaoTon/testrepo#4]
Test Comment
      <hr><em> ⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking</em><br><br><ul><li>LINK: utterances-link-to-docs</li><li>TAG: imodeljs-docs-question</li> </ul>

**Comment by githubUserTest12** [comment]
Adding a test comment to this issue.

**Comment by DanAbney** [comment]
should I be able to comment on a closed issue?

**Comment by BaoTon** [comment]
I think so!

**Comment by DanAbney** [comment]
Agreed, as long as it does not get lost on our end.

**Comment by DanAbney** [comment]
testing to see if the preview correct...
...compared to what is actually shown after submit?
